// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJMw4kklSckngDzrMctLSjIGUEtKUbYZE',
    appId: '1:699021114957:web:8583103acb93cfbb64a604',
    messagingSenderId: '699021114957',
    projectId: 'bookloopunimet-3273a',
    authDomain: 'bookloopunimet-3273a.firebaseapp.com',
    storageBucket: 'bookloopunimet-3273a.firebasestorage.app',
    measurementId: 'G-44T5LK2BFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDReBCt8wp-krXbgAzFJr9iw5bS28y8UA',
    appId: '1:699021114957:android:de7964e84a4d3f5c64a604',
    messagingSenderId: '699021114957',
    projectId: 'bookloopunimet-3273a',
    storageBucket: 'bookloopunimet-3273a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSdPcX_mxZT9esD9Bm2KGw-UamlD4ZJz8',
    appId: '1:699021114957:ios:36f1e632bb80b95e64a604',
    messagingSenderId: '699021114957',
    projectId: 'bookloopunimet-3273a',
    storageBucket: 'bookloopunimet-3273a.firebasestorage.app',
    iosBundleId: 'com.example.bookloopUnimet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSdPcX_mxZT9esD9Bm2KGw-UamlD4ZJz8',
    appId: '1:699021114957:ios:36f1e632bb80b95e64a604',
    messagingSenderId: '699021114957',
    projectId: 'bookloopunimet-3273a',
    storageBucket: 'bookloopunimet-3273a.firebasestorage.app',
    iosBundleId: 'com.example.bookloopUnimet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJMw4kklSckngDzrMctLSjIGUEtKUbYZE',
    appId: '1:699021114957:web:562ad9815cc5367664a604',
    messagingSenderId: '699021114957',
    projectId: 'bookloopunimet-3273a',
    authDomain: 'bookloopunimet-3273a.firebaseapp.com',
    storageBucket: 'bookloopunimet-3273a.firebasestorage.app',
    measurementId: 'G-JPYJRSKTFQ',
  );
}
